//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_Parent_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailedSubject
    {
        public int id { get; set; }
        public string regNo { get; set; }
        public string semester { get; set; }
        public string subject { get; set; }
        public string grade { get; set; }
    }
}
