//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_Parent_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string adminId { get; set; }
        public Nullable<double> attentive { get; set; }
        public Nullable<double> polite { get; set; }
        public Nullable<double> rudness { get; set; }
        public int hid { get; set; }
    }
}
