//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_Parent_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int hid { get; set; }
        public string regNo { get; set; }
        public string date { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string status { get; set; }
        public string reason { get; set; }
        public string adminId { get; set; }
        public string parentId { get; set; }
        public string referedTo { get; set; }
        public string suggestion { get; set; }
        public string adminFeedback { get; set; }
        public Nullable<double> parentRating { get; set; }
    }
}
