//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_Parent_Appointment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIIT_Parent_AppointmentEntities : DbContext
    {
        public BIIT_Parent_AppointmentEntities()
            : base("name=BIIT_Parent_AppointmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<CGPA> CGPAs { get; set; }
        public virtual DbSet<Disciplinary> Disciplinaries { get; set; }
        public virtual DbSet<FailedSubject> FailedSubjects { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<IssuesList> IssuesLists { get; set; }
        public virtual DbSet<LeaveLog> LeaveLogs { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<OTP> OTPs { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<WaitingList> WaitingLists { get; set; }
        public virtual DbSet<WaitingLog> WaitingLogs { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
    }
}
