//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_Parent_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public Nullable<int> code { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
    }
}
