//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_Parent_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string regNo { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string birthDate { get; set; }
        public string studentCNIC { get; set; }
        public string parentCNIC { get; set; }
        public Nullable<int> semester { get; set; }
        public string @class { get; set; }
        public string section { get; set; }
    }
}
