//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_Parent_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingList
    {
        public int id { get; set; }
        public Nullable<int> tsId { get; set; }
        public string regNo { get; set; }
        public string date { get; set; }
        public string reason { get; set; }
        public string parentId { get; set; }
        public string adminId { get; set; }
        public string status { get; set; }
    }
}
